### ISSUE TITLE
Crash of node-red when connecting to Zabbix 

### ISSUE THREAD

**Issue by trooster** [bashlakov/node-red-contrib-zabbix-sender#2]
Node-red crashes when  it connects to the Zabbix server.
I have set a default hostname, and the payload looks like this:

last_heartbeat = msg.payload
msg.payload = [
    "ajax.heartbeat",
    last_heartbeat
]
return msg;

This is the error making node-red crash:

10 Jan 20:37:24 - [red] Uncaught Exception:
10 Jan 20:37:24 - SyntaxError: Unexpected token Z in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/nodered/.node-red/node_modules/node-zabbix-sender/index.js:110:29)
    at Socket.emit (events.js:223:5)
    at TCP.<anonymous> (net.js:664:12)

Any ideas?

**Comment by trooster** [comment]
If someone else catches this error. I connected to port 10050 instead of 10051

**Comment by bashlakov** [comment]
@trooster, did you resolve your issue?

**Comment by trooster** [comment]
Yes, I did. If you connect to the wrong Zabbix port it crashes. But connecting to the correct port makes everything work smoothly.
