### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by Sergio-tix** [bashlakov/node-red-contrib-zabbix-sender#3]
How it works? I installed the node through the control panel. I am trying to send any data, for example:
`msg.payload = [
    "websrv",
    "httpd",
    1
]
return msg;
`
to the address zabbix server 192.168.1.222 port 10051, An error occurs "Error: connect ECONNREFUSED 192.168.1.222:10051".
![z1](https://user-images.githubusercontent.com/18720428/93028464-d6b62580-f61c-11ea-9bad-04f8766f6699.PNG)
![z2](https://user-images.githubusercontent.com/18720428/93028473-e03f8d80-f61c-11ea-898e-d3d75078e988.PNG)

**Comment by bashlakov** [comment]
Hi! Try to send data with zabbix_sender command line utility or check connection to zabbix server port 10051 with telnet from node-red host. Seems like network/firewall issue.

**Comment by Sergio-tix** [comment]
There was some internal problem with zabbix. Had to reinstall zabbix, now works fine.
